# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
import os

Import('CfgmEnv')
env = CfgmEnv.Clone()

base_path = '#controller/src/config/common/'
pkg = [
    env.SandeshGenPy('#controller/src/config/uve/service_instance.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/vnc_api.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/virtual_machine.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/virtual_network.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/physical_router.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/acl.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/cfgm_cpuinfo.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/greenlets.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/msg_traces.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/config_req.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/physical_router_config.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/service_status.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/feature_flags.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/config_api_worker.sandesh', base_path + 'cfgm_common/uve/', False),
    env.SandeshGenPy('#controller/src/config/uve/config_updater.sandesh', base_path + 'cfgm_common/uve/', False),
]

# Generate the sandesh cpuinfo from base
nodeinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/nodeinfo.sandesh', base_path + 'cfgm_common/uve/', False)
cpuinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/cpuinfo.sandesh', base_path + 'cfgm_common/uve/nodeinfo/', False)
process_info_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/process_info.sandesh', base_path + 'cfgm_common/uve/nodeinfo/', False)
env.Depends(nodeinfo_pkg, pkg)
env.Depends(cpuinfo_pkg, pkg)
env.Depends(process_info_pkg, pkg)

rel_path = Dir(base_path + 'cfgm_common').path
def BuildInfoAction(target, source, env):
    env.GenerateBuildInfoPyCode(path=rel_path)
build_info_rules = [env.Command(target=base_path+'cfgm_common/buildinfo.py', source=None, action=BuildInfoAction)]

sdist_depends = []
sdist_depends.extend(pkg)
sdist_depends.extend(nodeinfo_pkg)
sdist_depends.extend(cpuinfo_pkg)
sdist_depends.extend(process_info_pkg)
sdist_depends.extend(build_info_rules)

sources = ['setup.py', 'requirements.txt']
sources += env.AddPythonSources('cfgm_common', excludes=['uve'])

sdist_gen = env.Command(
    '/pip/cfgm_common-0.1.dev0-py3-none-any.whl', sources,
    'cd ' + Dir(base_path).path + ' && ' + 'python3 setup.py bdist_wheel --dist-dir /pip')
env.Depends(sdist_gen, sdist_depends)
env.Alias('install', sdist_gen)

deps = [
    '/pip/sandesh-0.1.dev0-py3-none-any.whl',
    '/pip/sandesh_common-0.1.dev0-py3-none-any.whl',
    '/pip/contrail_api_client-0.1.dev0-py3-none-any.whl',
]
env.SetupPyTestSuiteWithDeps(sdist_gen, sdist_depends=deps, top_dir=Dir(base_path).abspath)
