#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('AgentEnv')
env = AgentEnv.Clone()

AgentEnv.MakeTestEnv(env)

if GetOption('coverage'):
    env.Append(CPPDEFINES=['KSYNC_TEST_GCOV_DUMP'])

ksync_test_suite = []
ksync_flaky_test_suite = []

test_ksync_route = AgentEnv.MakeTestCmd(env, 'test_ksync_route', ksync_test_suite)
test_vnswif = AgentEnv.MakeTestCmd(env, 'test_vnswif', ksync_test_suite)
test_bridge_entry_audit = AgentEnv.MakeTestCmd(env, 'test_bridge_entry_audit',
                                               ksync_test_suite)
test_ksync_tcp = AgentEnv.MakeTestCmdSrc(env, 'ksync_tcp_test',
                                         ['ksync_tcp_test.cc',
                                          'ksync_test_util.cc'],
                                         ksync_test_suite)
test_ksync_sock_uds = AgentEnv.MakeTestCmdSrc(env, 'ksync_sock_uds_test',
                                              ['ksync_sock_uds_test.cc',
                                               'ksync_test_util.cc'],
                                              ksync_test_suite)

test_ksync_sock = AgentEnv.MakeTestCmdSrc(env, 'ksync_sock_test',
                                          ['ksync_sock_test.cc',
                                           'ksync_test_util.cc'],
                                          ksync_test_suite)
test_ksync_udp = AgentEnv.MakeTestCmdSrc(env, 'ksync_udp_test',
                                         ['ksync_udp_test.cc',
                                          'ksync_test_util.cc'],
                                         ksync_test_suite)
test_ksync_tx_queue = AgentEnv.MakeTestCmdSrc(env, 'ksync_tx_queue_test',
                                              ['ksync_tx_queue_test.cc',
                                               'ksync_test_util.cc'],
                                              ksync_test_suite)
flaky_test = env.TestSuite('agent-flaky-test', ksync_flaky_test_suite)
env.Alias('controller/src/vnsw/agent/ksync:flaky_test', flaky_test)

test = env.TestSuite('agent-test', ksync_test_suite)
env.Alias('agent:agent_test', test)
env.Alias('agent:ksync', test)
env.Alias('controller/src/vnsw/agent/ksync:test', test)
Return('ksync_test_suite')
