# -*- mode: python; -*-

#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#
# Placeholder for fabric-ansible Sconscript

Import('CfgmEnv')
env = CfgmEnv.Clone()

base_path = '#controller/src/config/fabric-ansible/ansible-playbooks/'

sdist_gen = env.Command(
    '/pip/fabric_ansible_playbooks-0.1.dev0.tar.gz', 'setup.py',
    'cd ' + Dir(base_path).path + ' && ' + 'python3 setup.py sdist --dist-dir /pip')

env.Alias('install', sdist_gen)

