# -*- mode: python; -*-

default = DefaultEnvironment()
env = default.Clone()

third_party_path = '#/third_party'
# hiredis from system package.
# we only buildthe boostasio adapter and our base64 helper
hiredis_asio_adapter_path = '#/third_party/hiredis-boostasio-adapter'

include = [third_party_path,
           '#/build/include', '#/third_party/tbb-2018_U5/include',
           '/usr/include']

env.Append(CPPPATH = include)
env.Append(CCFLAGS = ['-g'])
env.Append(LDFLAGS = ['-lssl', '-lcrypto'])
env.Append(LIBPATH = ['/usr/lib64', '/usr/lib'])
env.Append(LIBS = ['hiredis_ssl', 'hiredis'])

env.VariantDir('#/' + Dir('.').path + '/hiredis-boostasio-adapter', hiredis_asio_adapter_path)
hiredis_asio_adapter_buildpath = Dir('.').abspath + '/hiredis-boostasio-adapter'

boostasio_obj = env.Object(hiredis_asio_adapter_buildpath + '/boostasio.cpp')

lib = env.Library('hiredis_boostasio',
                  [boostasio_obj,
                  'base64.cpp']
                  )

env.Install('#/build/lib/', lib)
env.Install('#/build/include/hiredis', 'base64.h')
env.Install('#/build/include/hiredis', hiredis_asio_adapter_path + '/boostasio.hpp')
