# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
Import('CfgmEnv')
cniEnv = CfgmEnv.Clone()

cni_path = cniEnv.Dir('#/' + cniEnv.Dir('.').srcnode().path).abspath

def cniBuild(env, target, source):
    env.GoBuild(cni_path, './cmd/kube_cni')

gobin = cniEnv.Command(cniEnv['TOP'] + '/container/cni/bin/kube_cni', 'go.mod', cniBuild)

cniEnv.Alias('contrail-k8s-cni', gobin)
cniEnv.Alias('install', cniEnv.InstallAs(cniEnv['INSTALL_BIN'] + '/contrail-k8s-cni', gobin))
cniEnv.Default(gobin)
