#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

import sys
Import('AgentEnv')
env = AgentEnv.Clone()

env.CppEnableExceptions()
env.Append(CCFLAGS = ['-fexceptions'])

sources = [ 'agent_init.cc', 'agent_param.cc' ]
libvnswinit = env.Library('vnswinit', sources)

sources = [ 'agent_init.cc', 'contrail_init_common.cc', 'agent_param.cc' ]
libcontrail_init_common = env.Library('contrail_init_common', sources)

env.SConscript('test/SConscript', exports='AgentEnv', duplicate = 0)
