#
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# gmp_map directory

Import('GmpEnv')
env = GmpEnv.Clone()

env.CppEnableExceptions()
env.Append(CCFLAGS = ['-fexceptions'])

libgmp_map = env.Library('gmp_map', ['gmp_proto.cc', 'gmp_map.cc', 'task_map.cc'])

