# -*- mode: python; -*-
import os

vpath = '#/third_party/openvswitch-2.3.0'

env = DefaultEnvironment()
env['ENV']['CFLAGS'] = '-DOPEN_CONTRAIL_CLIENT -g'

config_opts = '--prefix=' + str(Dir('#/build'))

cmd = ('(cd ' + Dir('.').abspath + '; ' + str(Dir(vpath)) +
        '/configure' + ' ' + config_opts + '; make clean; make; make install)')

libs = [str(File('#build/lib/libopenvswitch.a'))]

openvswitch = env.Command('config.status', str(Dir(vpath)), cmd)

env.SideEffect(libs, openvswitch)

def Symlink(target, source):
    parent = os.path.dirname(target.abspath)
    if not os.path.exists(parent):
        os.makedirs(parent)

    try:
        if not os.path.exists(target.abspath):
            os.symlink(source.abspath, target.abspath)
    except:
        os.listdir(parent)

Symlink(Dir('#/build/include/openvswitch/include'), Dir(vpath + '/include'))
Symlink(Dir('#/build/include/openvswitch/lib'), Dir(vpath + '/lib'))
