# -*- mode: python; -*-
import platform
import sys

vpath = '#/third_party/bind-9.21.3/'
env = DefaultEnvironment()

build_dir = str(Dir('#/build'))
config_opts = '--prefix=' + build_dir + ' --enable-threads' + ' --enable-fixed-rrset'

cmd = ('(cd ' + Dir('.').abspath + '; ' + str(Dir(vpath)) +
        '/configure' + ' ' + config_opts + '; make clean; make; make install; ' +
        'cp -f ' + build_dir + '/sbin/named ' + build_dir + '/sbin/contrail-named; ' +
        'cp -f ' + build_dir + '/sbin/rndc ' + build_dir + '/sbin/contrail-rndc; ' +
        'cp -f ' + build_dir + '/sbin/rndc-confgen ' + build_dir + '/sbin/contrail-rndc-confgen;)')

incproducts = [
    '#build/include/dns/message.h',
    '#build/include/dns/view.h',
    '#build/include/dns/zone.h',
    '#build/include/dns/zt.h',
    '#build/include/ns/query.h'
]

libproducts = [
                str(File('#/build/lib/librndc'   + env['LIBSUFFIX'])),
                str(File('#/build/lib/libns'     + env['SHLIBSUFFIX'])),
                str(File('#/build/lib/libisc'    + env['SHLIBSUFFIX'])),
                str(File('#/build/lib/libisccc'  + env['SHLIBSUFFIX'])),
                str(File('#/build/lib/libisccfg' + env['SHLIBSUFFIX'])),
                str(File('#/build/lib/libdns'    + env['SHLIBSUFFIX'])),]

binproducts = [ str(File('#/build/sbin/contrail-named')),
                str(File('#/build/sbin/contrail-rndc')),
                str(File('#/build/sbin/contrail-rndc-confgen')) ]

allproducts = libproducts + binproducts + incproducts

bind_cfg = env.Command(allproducts, str(Dir(vpath)), cmd)

env.Alias('lib/bind:bind', bind_cfg)
env.Alias('install', env.Install(env['INSTALL_BIN'], binproducts))

