subdirs = [
    'bind',
    'gperftools',
    'gunit',
    'hiredis',
    'http_parser',
    'ipfix',
    'log4cplus',
    'openvswitch',
    'pugixml',
    'rabbitmq-c',
    'rapidjson',
    'SimpleAmqpClient',
]

for dir in subdirs:
    SConscript(dirs = dir, variant_dir = '#/build/third_party/' + dir)
